version: "3.8"

services:
  app:
    image: hocvoiai-fe:v1
    ports:
      - "3000:3000"
    restart: unless-stopped
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:4040"
    volumes:
      - website:/usr/share/nginx/html/website 