export const ReportType = {
  USER_REPORT: "USER_REPORT",
  ROADMAP_REPORT: "ROADMAP_REPORT",
  QUESTION_REPORT: "QUESTION_REPORT",
  QUESTION_REPLY_REPORT: "QUESTION_REPLY_REPORT",
  QUESTION_COMMENT_REPORT: "QUESTION_COMMENT_REPORT"
};
